#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-secure-web-proxy-policy
spec:
  info:
    title: Secure Web Proxy Policy
    source:
      sourceType: git
      git:
        repo: https://github.com/GoogleCloudPlatform/terraform-google-secure-web-proxy-policy
        dir: /
    version: 1.0.0
    actuationTool:
      type: terraform
      version: ">= 1.3"
    description:
      tagline: A Terraform module for creating Google Cloud Secure Web Proxy (SWP) Gateway Security Policies and Rules.
      detailed: This module simplifies the deployment of Google Cloud Secure Web Proxy resources. It creates a Gateway Security Policy, a set of configurable rules, and can optionally create a new Certificate Authority (CA) Pool for TLS inspection.
    icon: assets/icon.png
    diagrams:
      - name: architecture
        location: assets/architecture.png
    documentations:
      - title: Module README
        url: README.md
    examples:
      - name: simple_example
        location: examples/simple_example

  content:
    variables:
      - name: project_id
        description: The project ID to deploy the Secure Web Proxy resources in. If null, no resources will be created.
        type: string
        required: true
      - name: name
        description: The name for the Gateway Security Policy. If null, no resources will be created.
        type: string
        required: true
      - name: location
        description: The location for the Gateway Security Policy. This must be 'global'.
        type: string
        required: false
        default: "global"
      - name: description
        description: An optional description of this Gateway Security Policy.
        type: string
        required: false
        default: "Secure Web Proxy policy managed by Terraform."
      - name: create_tls_inspection_ca_pool
        description: If true, a new Certificate Authority (CA) Pool will be created for TLS inspection. If false, you can provide an existing CA Pool ID via 'tls_inspection_ca_pool_id'.
        type: boolean
        required: false
        default: false
      - name: tls_inspection_ca_pool_id
        description: The resource ID of an existing CA Pool to use for TLS inspection. This is used only when 'create_tls_inspection_ca_pool' is false.
        type: string
        required: false
        default: null
      - name: ca_pool_config
        description: Configuration for the CA Pool to be created if 'create_tls_inspection_ca_pool' is true.
        type: object
        required: false
        default:
          name: swp-tls-inspection-pool
          location: us-central1
          tier: DEVOPS
      - name: rules
        description: A list of rule objects to create for the Gateway Security Policy.
        type: array
        required: false
        default: []

    variableGroups:
      - name: Gateway Security Policy
        description: Core settings for the Gateway Security Policy.
        variables:
          - name
          - project_id
          - location
          - description
      - name: TLS Inspection
        description: Configuration for TLS inspection using a Certificate Authority (CA) Pool.
        variables:
          - create_tls_inspection_ca_pool
          - tls_inspection_ca_pool_id
          - ca_pool_config
      - name: Security Rules
        description: Define the rules to be applied by the security policy.
        variables:
          - rules

    outputs:
      - name: gateway_security_policy_id
        description: The fully qualified ID of the Gateway Security Policy.
      - name: gateway_security_policy_name
        description: The name of the Gateway Security Policy.
      - name: gateway_security_policy_rules
        description: A map of the created Gateway Security Policy Rules, keyed by rule name.
      - name: ca_pool_id
        description: The ID of the CA Pool created for TLS inspection, if any.

  requirements:
    roles:
      - level: project
        role: roles/networksecurity.admin
      - level: project
        role: roles/privateca.admin
    services:
      - networksecurity.googleapis.com
      - privateca.googleapis.com
