apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-secure-web-proxy
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-secure-web-proxy.git
  version: 1.0.0
  actuationTool:
    type: Terraform
    version: ">= 1.3"
  info:
    title: Google Cloud Secure Web Proxy
    description:
      tagline: A Terraform module to deploy Google Cloud Secure Web Proxy for centralized, secure web access.
      detailed: This module simplifies the deployment of a Google Cloud Secure Web Proxy (SWP) instance, including the gateway, a policy, and associated rules. It allows for configuring TLS inspection, custom IP addresses, and fine-grained traffic filtering rules based on CEL expressions.
    documentation:
    - title: "Module Documentation"
      url: "https://github.com/GoogleCloudPlatform/terraform-google-secure-web-proxy/blob/main/README.md"
    examples:
    - name: simple_gateway
      location: examples/simple_gateway
      title: Simple SWP Gateway with a Default Allow Rule
spec:
  terraform:
    variables:
    - name: certificate_manager_certificate
      description: "The full self-link of a Certificate Manager certificate to use for TLS inspection. e.g. projects/PROJECT_ID/locations/REGION/certificates/CERT_NAME"
      type: string
      required: false
      default: null
    - name: ip_address
      description: "The IP address of the gateway. This must be a valid, unused IP address from the proxy-only subnet. If not specified, an IP is automatically allocated."
      type: string
      required: false
      default: null
    - name: labels
      description: "A map of key/value labels to apply to the gateway and policy resources."
      type: map(string)
      required: false
      default: {}
    - name: location
      description: "The Google Cloud region where the Secure Web Proxy will be deployed."
      type: string
      required: true
    - name: name
      description: "The base name for the Secure Web Proxy gateway and its associated policy."
      type: string
      required: true
    - name: network
      description: "The full self-link of the VPC network to which the gateway is attached. e.g. projects/PROJECT_ID/global/networks/VPC_NAME"
      type: string
      required: true
    - name: policy_description
      description: "An optional description of the gateway policy."
      type: string
      required: false
      default: "Secure Web Proxy policy managed by Terraform."
    - name: policy_rules
      description: "A list of objects defining the rules for the Secure Web Proxy policy. Each object represents a rule. The 'action' can be 'ALLOW' or 'DENY'. The 'session_matcher' is a CEL expression."
      type: list(object)
      required: false
      default:
      - action: ALLOW
        description: A default rule to allow all traffic.
        enabled: true
        name: default-allow-all
        priority: 1000
        session_matcher: "true"
        tls_inspected: false
    - name: project_id
      description: "The project ID where the Secure Web Proxy and its components will be created."
      type: string
      required: true
    - name: subnet
      description: "The full self-link of the proxy-only subnet to which the gateway is attached. e.g. projects/PROJECT_ID/regions/REGION/subnetworks/SUBNET_NAME"
      type: string
      required: true
    outputs:
    - name: gateway_id
      description: "The full ID of the Secure Web Proxy gateway."
    - name: gateway_name
      description: "The name of the Secure Web Proxy gateway."
    - name: policy_id
      description: "The full ID of the Secure Web Proxy policy."
    - name: policy_name
      description: "The name of the Secure Web Proxy policy."
  requirements:
    services:
    - securewebproxy.googleapis.com
    - compute.googleapis.com
    - certificatemanager.googleapis.com
    roles:
    - level: project
      role: roles/securewebproxy.admin
    - level: project
      role: roles/compute.networkViewer
    - level: project
      role: roles/certificatemanager.viewer
